# Generated by Django 2.2.6 on 2019-11-02 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Owner_Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.City')),
                ('owner', models.ForeignKey(on_delete=models.SET('null'), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('code', models.IntegerField()),
                ('total', models.IntegerField()),
                ('owner_ship', models.ForeignKey(on_delete=models.SET('null'), to='application.Owner_Ship')),
            ],
            options={
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Date_Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('owner_ship', models.ForeignKey(on_delete=models.SET('null'), to='application.Owner_Ship')),
                ('reservation', models.ForeignKey(on_delete=models.SET('null'), to='application.Reservation')),
            ],
            options={
                'verbose_name_plural': 'Fechas de Alquileres',
            },
        ),
    ]
