# Generated by Django 2.2.6 on 2019-11-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Ciudades'},
        ),
    ]
