# Generated by Django 2.2.6 on 2019-11-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20191102_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_ship',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
