# Generated by Django 2.2.6 on 2019-11-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20191102_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_ship',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
