# Generated by Django 2.2.6 on 2019-11-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20191102_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_ship',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
