# Generated by Django 2.2.6 on 2019-11-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20191103_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_ship',
            name='image',
            field=models.ImageField(null=True, upload_to='application/img'),
        ),
    ]
