# Generated by Django 2.2.6 on 2019-11-08 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20191103_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_rent',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Reservation'),
        ),
    ]
