# Generated by Django 2.2.6 on 2019-11-08 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20191107_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_rent',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Reservation'),
        ),
    ]
