# Generated by Django 2.2.6 on 2019-11-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20191108_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_ship',
            name='date_in',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='owner_ship',
            name='date_out',
            field=models.DateField(null=True),
        ),
    ]
