# Generated by Django 2.2.7 on 2019-11-14 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0010_auto_20191114_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('null'), to=settings.AUTH_USER_MODEL),
        ),
    ]
