# Generated by Django 2.2.7 on 2019-11-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20191114_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_rent',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(),
        ),
    ]
